export const courses = [
  {
    id: 1,
    title: "Javascript zero to hero",
    description: "Lorem ipsum dolor sit amet",
    coverPhoto: "",
    price: 20,
    instructor: "Jonas",
    rating: 4.8,
    students: 147570,
  },
  {
    id: 2,
    title: "Vue js mastery",
    description: "Lorem ipsum dolor sit amet",
    coverPhoto: "",
    price: 11,
    instructor: "ZTM",
    rating: 4.3,
    students: 2044,
  },
  {
    id: 3,
    title: "Think in a React Way",
    description: "Lorem ipsum dolor sit amet",
    coverPhoto: "",
    price: 15,
    instructor: "Sumit",
    rating: 4.8,
    students: 75002,
  },
  {
    id: 4,
    title: "Learn Mern Stack with PH",
    description: "Lorem ipsum dolor sit amet",
    coverPhoto: "",
    price: 16,
    instructor: "Jhankar",
    rating: 4.7,
    students: 50000,
  },
  {
    id: 5,
    title: "Node Js all need to know",
    description: "Lorem ipsum dolor sit amet",
    coverPhoto: "",
    price: 13,
    instructor: "Nayeem",
    rating: 4.5,
    students: 20000,
  },
  {
    id: 6,
    title: "TypeScript for absolute beginner",
    description: "Lorem ipsum dolor sit amet",
    coverPhoto: "",
    price: 10,
    instructor: "Bhadon",
    rating: 4.1,
    students: 3200,
  },
];
